# For more info on OperatorGroups
# See https://github.com/operator-framework/operator-lifecycle-manager/blob/master/Documentation/design/operatorgroups.md
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: opendatahub-operator
  namespace: opendatahub
spec:
  targetNamespaces:
  - opendatahub
