apiVersion: operators.coreos.com/v1
kind: CatalogSourceConfig
metadata:
  name: redhat-operators-my-namespace
  namespace: openshift-marketplace
spec:
  csDisplayName: Red Hat Operators
  csPublisher: Red Hat
  packages: amq-streams
  targetNamespace: my-namespace