apiVersion: sources.eventing.knative.dev/v1alpha1
kind: KafkaSource
metadata:
  name: sensorstream-source-raw
spec:
  consumerGroup: syndesis-raw
  bootstrapServers: demo2019-kafka-bootstrap.strimzi-demo.svc.cluster.local:9092
  topics: sensorstream-raw
  net:
    tls:
      enable: false
  sink:
    apiVersion: serving.knative.dev/v1alpha1
    kind: Service
    name: sensor-to-damage